application: theme-designer
version: 1
runtime: python27
threadsafe: true
api_version: 1


handlers:
- url: /js
  static_dir: static/js
- url: /bootstrap
  static_dir: static/bootstrap
- url: /css
  static_dir: static/css
- url: /
  static_files: templates/index.html
  upload: templates/index\.html

- url: /_ah/spi/.*
  script: api.theme.APPLICATION

libraries:
- name: numpy
  version: "1.6.1"
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest
